# services:
#   sqlserver:
#     image: mcr.microsoft.com/azure-sql-edge:latest
#     container_name: sqlserver
#     environment:
#       - ACCEPT_EULA=1
#       - MSSQL_SA_PASSWORD=GucluSifre!!!
#     ports:
#       - "1433:1433"
#     volumes:
#       - ./mssql-data:/var/opt/mssql
#     restart: unless-stopped